### ISSUE TITLE
Mobile view - logo displayed under top nav

### ISSUE THREAD

**Issue by 22nds** [opensourcediversity/opensourcediversity.org#10]
On mobile view (<=575px) the main logo needs more margin at the top, because now the top header is covering it. 

I would suggest we add:
```
margin: 60px 0 40px 0;
```

![screenshot_20180530-120923](https://user-images.githubusercontent.com/1879220/40714317-98d833ba-6402-11e8-8e06-08837bb602c4.png)

**Comment by sleepypioneer** [comment]
💯 sounds good to me, @22nds feel free to make a pull request. Ask @jancborchardt to review it.
