### ISSUE TITLE
Text alignment for class text-center should be set center

### ISSUE THREAD

**Issue by nikolatechie** [opensourcediversity/opensourcediversity.org#107]
Currently, text alignment in class text-center is set to _left_. It should be set to _center_ because it looks better visually and the class name says so.

**Comment by Roshanjossey** [comment]
> It should be set to center because it looks better visually

I've to disagree. I think it's more readable with left align

_left align_

![image](https://user-images.githubusercontent.com/8488446/93468416-3ba89e80-f8ef-11ea-95a1-1d52b2d91df0.png)


_center align_

![image](https://user-images.githubusercontent.com/8488446/93468477-524ef580-f8ef-11ea-87bd-66567eb2e135.png)

> class name says so.

https://github.com/opensourcediversity/opensourcediversity.org/blob/master/css/custom.css#L303
This rule doesn't mean `text-center` gets the style `align: left`.
It means that the `li` and `p` inside `col-md-4` inside `text-center` gets that style. That doesn't go against the name `text-center`.

`text-center` gets it's styles from bootstrap

**Comment by nikolatechie** [comment]
What about these?
<br><i>left align:</i>
![Screenshot_1](https://user-images.githubusercontent.com/13731532/93473901-e1abd700-f8f6-11ea-8621-29843b239cd1.png)
<br><i>center align:</i>
![Screenshot_2](https://user-images.githubusercontent.com/13731532/93473906-e3759a80-f8f6-11ea-8997-5943b59293ac.png)

Look below "Heart of Code Berlin". When the text below it isn't centered, it really looks bad.

**Comment by Roshanjossey** [comment]
I agree with you in the case of `Heart of Code Berlin`. However, when there's more than 3 lines, I see that left align is better.
