### ISSUE TITLE
Request to join this organisation.

### ISSUE THREAD

**Issue by akshitagupta15june** [opensourcediversity/opensourcediversity.org#112]
I Would like to join this organisation.
I love open source and will love to contribute in this organisation.
Please add me in your organisation.
My Github handle akshitagupta15june

**Comment by jwflory** [comment]
Hi @rutujak24, thank you for your interest on Open Source Diversity! If you are interested in learning more about us and getting involved, I recommend introducing yourself in [our Telegram channel](https://t.me/diversityandinclusioninoss) or on the [Discourse forum](). Hope to see you in one or both of those places. 🙂 Thank you for your patience in receiving a response.
