### ISSUE TITLE
Yourfirstpr repository has been archived, removal from basics section

### ISSUE THREAD

**Issue by everly-gif** [opensourcediversity/opensourcediversity.org#115]
Yourfirstpr repository has been archived, removing it from the basics section of the website seems to be a better idea.

**Comment by Ahcatan** [comment]
can you explain? I dont understand what has been archived

**Comment by jonatoni** [comment]
@everly-gif thanks, good point. We should remove it. 

@Ahcatan we should remove https://yourfirstpr.github.io/ from our website

**Comment by everly-gif** [comment]
Hey @jonatoni  I can work on this, could you assign me this.

**Comment by everly-gif** [comment]
@jonatoni  made a pull request, do review it. Thanks!
