### ISSUE TITLE
No scroll when items are clicked on navigation bar (CROSS BROWSER ISSUE)

### ISSUE THREAD

**Issue by Guneetsinghtuli** [opensourcediversity/opensourcediversity.org#126]
The  **[scroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior)** CSS is not supported in SAFARI because of which smooth scroll animation is not working 

REFER TO: css/custom.css -> [48,5]

https://user-images.githubusercontent.com/48324492/119508658-89827a00-bd8d-11eb-8221-3f786f445de1.mov

**Comment by SANJAY072000** [comment]
I have done a PR #127 to this issue.
