### ISSUE TITLE
Migrate site to React-based framework, like Docusaurus

### ISSUE THREAD

**Issue by jwflory** [opensourcediversity/opensourcediversity.org#131]
# Summary

Convert the existing website (plain HTML page) into a React-based site focused on content management, such as [Docusaurus](https://docusaurus.io/)

# Background

When the `opensourcediversity.org` website was first created, we were a smaller project with a group of people that also had in-person meet-ups to work on things like the website. Fast forward a few years and add a global pandemic in, and our site is tough to maintain in its current form.

Since there is a lot of interest in the site, and we have not made significant content changes in some time, now is a good opportunity to evaluate what we want to do. There are two goals in making a big change like this:

1. **Exciting web technologies**: Use a web framework or tool that has some popularity, in the hope of getting more people involved who want to learn more about that kind of technology.
2. **Content management**: Improve ease of maintenance for the resources, suggestions, and referrals we share on our website. Split up content so it is not maintained in one long HTML file.

# Details

There are two sub-components to this mini-project:

## Exciting web technologies

React is a popular front-end tool used in many communities, and [Docusaurus](https://docusaurus.io/) is a React-based documentation tool written with close integration to upstream React. There are opportunities for us to figure out style and branding designs not only for this website, but any other websites we would want to build or host in the future.

## Content management

Once the content is divided into smaller files that are easier to maintain, we can begin more active curation and review of what content is on our site. Are some resources outdated? Should we remove them? Are there new sections or new resources we can add? Where do they go?

We will need a small group of folks with an interest in this work to help out. Think of it like a librarian sort of task? :eyes: 

# Outcome

`opensourcediversity.org` is easier to contribute to, and it is easier for us to create and maintain a resource for and by the community

**Comment by Victorybrown** [comment]
Can you explain more on the Content Management. What is expected? Are we to research and curate resources to improve and promote Open Source D & I or Organize already existing resources? Is it a technical contribution involving codes or just writing?

**Comment by IamJayashree** [comment]
Hi Justin, I would like to understand more about the content management work. would like to contribute accordingly. thank you

**Comment by Aashimalik** [comment]
Hi All,
I would love to be part of it. I'm working as a full stack developer .

**Comment by jancborchardt** [comment]
Before diving into the technical details, it would make sense to define how the site should look like and what kind of content we want to offer. Based on that we can make a better choice regarding the technology.

(Ultimately we could also do it with Vanilla JS and JSON for the data so it's very approachable.)

**Comment by IamJayashree** [comment]
Hi Team, I have about 7 front end engineers from my team who are interested to contribute. They will be commenting here soon. Let us know if any meeting required once the team shares their consensus here.

**Comment by soumya-wipro** [comment]
Hi Team,
This is Soumya Bose. I am a full stack developer. I am looking forward to contribute my free time in this project.

**Comment by krish5512** [comment]
Hi All,

I am haves started on the MERN stack and would love to contribute my free time in this project

**Comment by kavitha89** [comment]
Hey Team,

I will be more than happy to help out here at this space. Let me know. Thank You!

**Comment by strivedi07** [comment]
Hi Team,

I am new to React but keen to learn and contribute in this project.

**Comment by jwflory** [comment]
> _**@Victorybrown wrote…**_
> Can you explain more on the Content Management. What is expected? Are we to research and curate resources to improve and promote Open Source D & I or Organize already existing resources? Is it a technical contribution involving codes or just writing?

> _**@IamJayashree wrote…**_
> Hi Justin, I would like to understand more about the content management work. would like to contribute accordingly. thank you

Hi @Victorybrown and @IamJayashree, I was thinking more like a knowledge-base, something [like this kind of example](https://unicef.github.io/inventory/). Right now, we have a few sections on our website that provide resources or referrals. We could push this one step further by better curating our existing content into a static site generator tool that works with Markdown source files. Then, we could brainstorm further on ideas for topics not yet covered. It gives people a chance to then share knowledge and advice as they see fit.

However, I feel like we need to first start by migrating the existing content to a new tool or framework, so we know what options and features are in place for us to utilize with the content.

I could open new GitHub issues for each section so folks could take a lead on content review and updating what we have already published on `opensourcediversity.org`. What do you think?

> _**@jancborchardt wrote…**_
> Before diving into the technical details, it would make sense to define how the site should look like and what kind of content we want to offer. Based on that we can make a better choice regarding the technology.
>
> (Ultimately we could also do it with Vanilla JS and JSON for the data so it's very approachable.)

Good point! Would it help for me to open a new issue on creating mock-ups or wireframes first? What do you think @jancborchardt?

> _**@soumya-wipro wrote…**_
> This is Soumya Bose. I am a full stack developer. I am looking forward to contribute my free time in this project.

> _**@krish5512 wrote…**_
> I am haves started on the MERN stack and would love to contribute my free time in this project

> _**@kavitha89 wrote…**_
> I will be more than happy to help out here at this space when its related to frontend and React. Let me know. Thank You!

> _**@strivedi07 wrote…**_
> I am new to React but keen to learn and contribute in this project.

Great, thanks all for commenting here! Stay tuned for more information as we get this project going. It will be a discussion topic at our next monthly meeting on July 14th.

**Comment by IamJayashree** [comment]
Thanks @jwflory  - On your response on the content management , would request you to take sometime to explain during our monthly meeting please.  Plus, let me know if you need our volunteers ( reactJS devs) to attend.

**Comment by jwflory** [comment]
Hi @opensourcediversity/website-committers (@ramyaparimi, @Aashimalik, @krish5512, @soumya-wipro) and invited folks (@ashlyn-knox @IamJayashree @kavitha89 @strivedi07), you are now part of the team. Welcome aboard!

Please take a look at [this forum post](https://discourse.opensourcediversity.org/t/modernizing-opensourcediversity-org-developers-and-content-creators-wanted/605/3?u=jwf) summarizing the last meeting's discussion on the website.

Two notes of highlight:

> We will need to set up a developer meeting to begin next steps to work on the website. We will begin with a requirements gathering exercise to guide us on next steps. We should begin working on a timeline to present back to the community at the next August monthly meeting.
>
> [I also created a Telegram group for developers.](https://t.me/joinchat/YFfGxuVL2ug3ZWYx)

When you get a chance, please join the Telegram group and say hello! Hope to chat with you all there soon. 🙂

**Comment by IamJayashree** [comment]
Thank you Justin

**Comment by IamJayashree** [comment]
Our engineering crew have joined Telegram.

**Comment by LaideLawal** [comment]
I am interested, I would be glad if you can count me in

**Comment by jordanwangdev** [comment]
I would like to contribute to this migration too.

**Comment by jonatoni** [comment]
I am closing this issue as stale for now. @jwflory we can create a new issue when we start working on it.
