### ISSUE TITLE
 Please invite me to the GitHub Organization

### ISSUE THREAD

**Issue by Jyoti-prakash-rout** [opensourcediversity/opensourcediversity.org#134]
I'm a Web Dev enthusiast & a junior pursuing my Bachelors in Computer Science & Engineering. I'm interested in Web Devlopment, Machine Learning & DevOps & I enjoy learning new things & stuff as well as I'm a Frontend Devloper with experience building Dynamic & Static Web pages. I am always interested in learning the answers to how, why, and what relates to the Technologies around me.

I would like to grow my programming skills by doing lots of Open Source contributions. Looking forward to learning, collaborating, and growing as a community.

**Comment by jwflory** [comment]
Hi @Jyoti-prakash-rout, our community presence is less on GitHub. Please join us either [on Telegram](https://t.me/diversityandinclusioninoss) or [on Signal](https://signal.group/#CjQKIBCrnNZU2ROCBP5ysJgdiYJBPNxIKT3tkktcMTywdgOUEhBbZbRk0doCcoAGC6Vauv14) and share your introduction there. Thanks, hope to see you there. 🙂
