### ISSUE TITLE
Transparency issue: who pays the bills?

### ISSUE THREAD

**Issue by Shamar** [opensourcediversity/opensourcediversity.org#135]
Hi, I'm having a hard time to find any information about the funding of opensourcediversity.org since it's foundation.

Can you please add a page or a section about your funders like many other organizations do for transparency (see for example https://fsfe.org/donate/thankgnus.en.html )

**Comment by jwflory** [comment]
Hi @Shamar, Open Source Diversity isn't a foundation or any kind of legally-registered organization. It is a general community that has formed up around the website and community chat channels. We don't have any formal funders, although there is the Open Collective managed by @jancborchardt which has helped to pay for infrastructure costs over years. Nobody is paid for their contributions and everyone who has participated over the years has done so as a volunteer.

Hope this answers your question.

**Comment by Shamar** [comment]
Uhm... thanks for your answer @jwflory.

To be honest, I think such kind of structure should be documented on the website as well, since a [newcoming contributor](https://github.com/opensourcediversity/opensourcediversity.org/pulls) or a [donor over open collective](https://opencollective.com/opensourcediversity) might not be aware to be donating to a informal group of private individuals.

For one, I would have supposed this group to be at least a no-profit association.

Anyway I have a further question prompted directly from your answer: who signed this letter on behalf of your whole community back in March?
https://github.com/rms-open-letter/rms-open-letter.github.io/commit/260b260a81f6033f795d1f51fcd081a94a5bf0e8

I see your signature was added by @zacchiro together with other well known and structured foundations, and to be honest I thought Open Source Diversity had a similar structure and weight of the others.

Maybe it's just a case of homonymy?

**Comment by jwflory** [comment]
We have active Signal and Telegram groups where we discussed making such a collective signature.

**Comment by Shamar** [comment]
Cool! Even Debian voted about signing that letter!
It's much more democratic than how other projects are managed.

I'm not much fan of centralized social networks, so I avoid both Signal and Telegram.
Unfortunately [the forum doesn't look much active](https://discourse.opensourcediversity.org/latest) and even the [twitter account](https://twitter.com/osdiversity) post roughly once a month just to account for donations.

So may I ask how many people are active on such channels on a daily basis?
