### ISSUE TITLE
 Contributor Code of Conduct - Link - Error

### ISSUE THREAD

**Issue by GiaPhuoc** [opensourcediversity/opensourcediversity.org#148]
The link of "[Contributor Code of Conduct]" inside the footer of Open Source Diversity website is link to "404 Error Not Found"
Someone please fix this error 

![image](https://user-images.githubusercontent.com/79918227/226757377-f5373100-5980-4c31-9113-b0841cf5e239.png)

**Comment by PhuocOng** [comment]
I just help you fix the problem, now we wait for the approving

**Comment by Shu12388y** [comment]
Hello, can you assign this issue to me I can solve this
