### ISSUE TITLE
Broken link on the web site

### ISSUE THREAD

**Issue by Ahcatan** [opensourcediversity/opensourcediversity.org#160]
Hi I just noticed there was a broken link here https://opensourcediversity.org/ for "diversity tickets["](https://diversitytickets.org/)
I don't know how to fix that myself, sorry.

**Comment by Nyumat** [comment]
It looks like their website is down. [diversitytickets.org](https://diversitytickets.org/)

Confirmed with alternative link from their Twitter bio which you can find, [here.](https://twitter.com/diversitytix?lang=en)

I think the best bet is removing them from the landing page all together. 

As we see in their repository, it's looking like  a [ghost town/inactive.](https://github.com/rubymonsters/diversity_ticketing) The grid of projects mentioned in this repo's `src` also has a single image element in that row, so I also imagine it will look more uniform as a grid of images by removing Diversity Tickets.

It's so sad to see that their project seems to have faded. 😔

**Comment by Nyumat** [comment]
Image for proof:

![image](https://github.com/opensourcediversity/opensourcediversity.org/assets/46255836/b262eafa-2066-4af7-8d9b-82352f19209d)

**Comment by Nyumat** [comment]
I will open a PR that fixes this, we'll see what happens.

**Comment by jonatoni** [comment]
Thanks for the your work on this @Nyumat :tada:
