### ISSUE TITLE
Hover on `contribute` link in events makes it hard to click the link for twitter account

### ISSUE THREAD

**Issue by MylesBorins** [opensourcediversity/opensourcediversity.org#2]
the hot zone when hovering over the `contribute` link makes it near impossible to click on the link for the twitter account.

I would submit a patch but unfortunately as a google employee I am [not permitted](https://opensource.google.com/docs/patching/#forbidden) to patch AGPL projects. If there is interest in changing licenses I am more than happy to open another PR with some suggestions.

**Comment by jancborchardt** [comment]
@MylesBorins yep, this has been fixed in a recent update. :) (Also reported at https://gitlab.com/opensourcediversity/opensourcediversity.org/issues/5)

> I would submit a patch but unfortunately as a google employee I am [not permitted](https://opensource.google.com/docs/patching/#forbidden) to patch AGPL projects.

Wow, that’s interesting info, also unfortunate. :\

**Comment by MylesBorins** [comment]
@jancborchardt let me know if you are open to exploring other licenses and I can open an issue. (also lmk if you prefer the issue to be opened on gitlab
