### ISSUE TITLE
Include Twitter Feed on page

### ISSUE THREAD

**Issue by sleepypioneer** [opensourcediversity/opensourcediversity.org#3]
Use Twitter API to add latest tweets from Open Source Diversity to the website. 

Need to decide where this should go on page. Also include a follow button?

**Comment by drashti4** [comment]
I can not find Github, Twitter and Slack icons in mobile UI. Are you going to fix that? I would happy to contribute.

**Comment by jancborchardt** [comment]
@drashti4 oh, they should be in the menu, where Events, Articles etc are too – could you open a separate issue about that? Pull request to fix it is also welcome. :) The set up instructions are in the readme, and feel free to ask if you need help (but let's do that in a new issue). :)
