### ISSUE TITLE
Add Women Tech Makers

### ISSUE THREAD

**Issue by sara-02** [opensourcediversity/opensourcediversity.org#33]
Women Tech Makers can be added under either space or programs or both.
 It is a global community with local chapters and runs the annual Google Women Tech makers Scholarship that is open worldwide(region based)
Women Tech Makers Community: https://www.womentechmakers.com
Women Tech Makers Scholarship: https://www.womentechmakers.com/scholars

**Comment by jancborchardt** [comment]
Good question actually if Women Tech Makers belongs on the list as it's not really about open source – or is it?

There's an issue at #37 where we could discuss our criteria for adding projects. Please join the discussion @sara-02! :)

**Comment by sara-02** [comment]
Closing this issue, w.r.t to the information provided in #37.
