### ISSUE TITLE
Add GHC, GHCI and Tapia Conferences under Program Sections

### ISSUE THREAD

**Issue by sara-02** [opensourcediversity/opensourcediversity.org#34]
Both the Grace Hopper Conferences(GHC and GHCI) and the Tapia Conference are excellent opportunities for women for presenting their work, and networking with other professionals, students and companies from around the world. Both conferences are held annually. GHC has a sister conference held annually in India, called Grace Hopper Conference India(GHCI).
All the 3 conferences are largely for promoting diversity and inclusion.
GHC: https://ghc.anitab.org/
Tapia: http://tapiaconference.org/
GHCI: https://ghcindia.anitab.org/

All these conferences have a travel scholarship awarded to students and academicians.

**Comment by sadetavarez** [comment]
Hello, 
Is this issue still available to work on? I would like to complete this task.

**Comment by jancborchardt** [comment]
It seems the conferences are not really related to open source, or am I missing something? :slightly_smiling_face:
Also all of them are already supported by AnitaB.org, which is a similar organization but with diversity in tech overall as a goal. We focus on diversity in open source specifically as there’s much less going on.

cc @camilasan @jonatoni @alicetragedy what do you think?

**Comment by alicetragedy** [comment]
I agree — I'm not very familiar with these conferences myself, but it sounds to me like they're pretty general and not specifically for Open Source. :)

**Comment by sara-02** [comment]
Yes, they are general WIT conference and not related to open source. @sadetavarez I am closing this issue.

**Comment by jonatoni** [comment]
+1 with @alicetragedy

**Comment by jancborchardt** [comment]
@sara-02 I added them to the list at **Criteria for adding projects / About page with other related projects #37**. :) Then we can still list them once we have a page with related projects.

**Comment by sara-02** [comment]
@jancborchardt Cool, we can reopen the issue once we get there :)
