### ISSUE TITLE
Criteria for adding projects / About page with other related projects

### ISSUE THREAD

**Issue by jancborchardt** [opensourcediversity/opensourcediversity.org#37]
A start at an attempt of what our criteria for selecting projects is. :) This could be the start of an "About" page.

Our short description is: **For more diversity & inclusion in free & open source software communities 😊**

- **Open Source:** Not only about diversity in tech generally, like
   - https://www.diversifytech.co, https://www.womenwhocode.com/, https://anitab.org/, https://www.girldevelopit.com/, http://www.blackgirlscode.com/, https://www.globaldiversitycfpday.com/, https://www.ladiesofcode.com/, Women Techmakers, http://www.women2.com, http://werocktech.com  – even http://www.womeninlinux.com/ is not that much about free & open source software
   - Conferences: GHC https://ghc.anitab.org/, Tapia http://tapiaconference.org/, GHCI https://ghcindia.anitab.org/
   - Coding language groups not specific to open source: PyLadies, RailsGirls, Djangogirls, http://phpwomen.org/,
- **Diversity:**
    - Not only about getting newcomers involved in tech (OpenTechSchool, Codebar, FreeCodeCamp etc)
    - Not only women*, also people of color, people with disabilities, and other underrepresented groups

There are a lot of other lists already about general tech diversity initiatives:

- Tech initiatives for marginalized groups: https://gist.github.com/anikalindtner/9524950
- https://github.com/jamiehannaford/diversity
- https://github.com/cristianoliveira/awesome4girls
- https://github.com/folkswhocode/awesome-diversity
- https://github.com/piamancini/diversity-resources
→ **That's why we should really focus on the intersection of _open source_ and diversity & inclusion**
 

What do you think @camilasan @jonatoni @sleepypioneer @emmairwin @incabell @sara-02 everyone? :)

**Comment by camilasan** [comment]
> Not sure about this one: Should we include initiatives which are about coding only or a specific language like PyLadies, RailsGirls, Djangogirls, http://phpwomen.org/, OpenTechSchool? Cause we should also highlight non-code ways of contributing.

I think they also fall under "is not that much about free & open source software".
