### ISSUE TITLE
Set up group on Open Collective for donations? (sticker costs, domain, etc)

### ISSUE THREAD

**Issue by jancborchardt** [opensourcediversity/opensourcediversity.org#38]
Maybe it would make sense for us to be on [Open Collective](https://opencollective.com)? That way we can do funding for sticker printing, domain costs etc. We do that with Open Source Design and it works quite well: https://opencollective.com/opensourcedesign/ – what do you think?

On the application page at https://opencollective.com/opensource/apply they say that:

> You'll need a GitHub account and a repository with over 100 stars.

So if we would like to be on there we should get people to star this repository. :)

Also cc @piamancini from Open Collective – is the 100 stars a hard requirement? We have almost 500 Twitter followers ;) https://twitter.com/osdiversity

**Comment by piamancini** [comment]
hi @jancborchardt - The 100 stars restriction has more to do with software projects. Please apply with any other tag than open source. We'd love to host this on the Open Source Collective.

**Comment by piamancini** [comment]
done - opencollective.com/opensourcediversity

**Comment by jancborchardt** [comment]
Yay, thank you so much! Adjusted the design and added a bunch of us to the collective: https://opencollective.com/opensourcediversity#

cc @camilasan @Incabell @GretaD @jonatoni @kristiprogri @sleepypioneer @evalica – feel free to add others too. :)

By the way @piamancini, since you also authored things like https://github.com/piamancini/diversity-resources, I’d like to add you to this Github org and the collective too, is that ok? :)

**Comment by piamancini** [comment]
totally!

**Comment by piamancini** [comment]
quick note that I will be showcasing this collective on the open collective newsletter coming out this week. I'll use your language from the website, do let me know if I should highlight anything in particular!

**Comment by jancborchardt** [comment]
@piamancini wow, that's so cool, thank you a ton! :) Using the language from website and/or Open Collective page is perfect!

**Comment by jancborchardt** [comment]
Closing as this is successfully done! :)

- This pull request adds Open Collective to the website: https://github.com/opensourcediversity/opensourcediversity.org/pull/63
- This pull request adds backers and contributors to the readme: https://github.com/opensourcediversity/opensourcediversity.org/pull/45

Please review :tada:
