### ISSUE TITLE
Add articles about ageism in tech

### ISSUE THREAD

**Issue by camilasan** [opensourcediversity/opensourcediversity.org#41]
I have discussed with @jancborchardt about it.
We usually talk mostly about sexism and racism, but we should also try to highlight ageism.

**Comment by camilasan** [comment]
#42

**Comment by JKolodny** [comment]
@camilasan if this issue is still open, I would love to do some research/find articles related to this. Thanks!

**Comment by camilasan** [comment]
@JKolodny You should ask @jancborchardt about it.

**Comment by jancborchardt** [comment]
Sure @JKolodny, it would be great if you can do some research on this. :) When looking for articles, there are probably a lot of article about ageism in tech. So best make sure that they are about ageism specifically to open source, as this is more relevant to our project.

**Comment by JKolodny** [comment]
@jancborchardt Okay, I'll get on it! Thanks :)
