### ISSUE TITLE
Add articles about people with disability in open source

### ISSUE THREAD

**Issue by camilasan** [opensourcediversity/opensourcediversity.org#42]
Like https://www.inc.com/zoe-henry/aapd-disability-equality-index-2017.html...
It is in the same line as [ageism](#41), we don't talk about it but it is also a form of exclusion.

**Comment by jancborchardt** [comment]
It would be great to have something specific to open source even. Regarding what to do about it, the Mozilla Developer Network page on [What is accessibility](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility) is pretty great! 

Another possible good resource is these posters on [designing for accessibility](https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/).
![](https://accessibility.blog.gov.uk/wp-content/uploads/sites/52/2016/08/Karwai-blog-1-1.png)
They help make clear where difficulties lie and how to fix them.

**Comment by camilasan** [comment]
> It would be great to have something specific to open source even. 

That is what I meant :)

**Comment by jancborchardt** [comment]
Just remembered this article from some time ago, from Liz Henry of Mozilla:
https://longmoreinstitute.wordpress.com/2017/09/11/theres-always-something-to-be-done-liz-henry-on-being-disabled-in-tech/
It’s also not super-specific to open source, but it’s nice and has some good further reading too.

**Comment by R-Ligier** [comment]
Hi there, I am interested in working on this issue if it is still available.

Can someone provide some more details on the kinds of articles the project is looking to add?

**Comment by jancborchardt** [comment]
Hi @R-Ligier, welcome! :) In general we want to highlight resources on the intersection of diversity/inclusion _and_ open source.

There’s a lot of resources about diversity/inclusion in _tech_, but as there’s also already many projects focused on aggregating those, we specifically want to focus on open source.

@camilasan what do you think, did I forget anything?

**Comment by prologic** [comment]
A good friend of mine @pdurbin pointed me to this issue and your efforts (_thank you btw_). Just wanted to say that I am a person with a vision impairment (_legally blind actually_) and I've been contributing to and developing open source projects for quite some time. I'm now a proud member of  a new company I recently joined ([NetData](https://netdata.cloud)) that embraces OSS and the Maintainer culture that you typically find in Open Source.

That said; Let me know if I can help in any way... Perhaps I could write a blog post on my [blog](https://prologic.blob) or help contribute to said article :)

**Comment by jancborchardt** [comment]
Very cool, welcome @prologic! As we are mainly a platform which aggregates things: Are you aware of specific articles or resources on the intersection of open source and accessibility which we don’t list on https://opensourcediversity.org yet? Important is that it’s both topics, not one or the other, or just "accessibility in tech".

Also, we have a forum at https://discourse.opensourcediversity.org – including an introductory thread where you can say hello :)

**Comment by toddswrittenword** [comment]
> designing for accessibility

Are you accepting blog/article submissions for this?  Or are you only looking for curated links?  I ask because I have a background in disability law.

**Comment by jancborchardt** [comment]
@toddswrittenword since we are mainly an aggregator and don’t necessarily want to get into content production ourselves, we’d rather link it, as it is now at https://opensourcediversity.org/#articles :)

(Just like for the events: We did do some where needed, especially to connect communities, but we’d also rather highlight existing relevant ones.)

**Comment by toddswrittenword** [comment]
Sounds good!


--------------------------------

Todd Brogowski
Todd’s Written Word, LLC
www.toddswrittenword.com
todd@toddswrittenword.com
719-749-1160

Intelligent Content That Inspires, Sells, and Informs

**Comment by N00Bmaster2810** [comment]
Hi, I am interested in working on this issue if it is still available.

**Comment by Kerveyfelix** [comment]
Can I add an article?

**Comment by Abiola-Farounbi** [comment]
Is this issue still open

**Comment by Amritpal-001** [comment]
Hi, I am interested in working on this issue.

**Comment by FAMOUSCLEAN** [comment]
> Like https://www.inc.com/zoe-henry/aapd-disability-equality-index-2017.html... It is in the same line as [ageism](#41), we don't talk about it but it is also a form of exclusion.

I believe there are many on disability that have no idea they can contribute and make as much and in most cases more while gaining skills and confidence.

**Comment by FAMOUSCLEAN** [comment]
I believe one must promote  the work as stated rejuvenating the senses for a sense of being good enough.

**Comment by Ayushbajpai19** [comment]
Can i work on this issue as part of hacktoberfest?

**Comment by sleepypioneer** [comment]
The article from Liz Henry was added but the link seems to be broken, it can be updated to this [link](https://longmoreinstitute.sfsu.edu/archive/there%E2%80%99s-always-something-be-done-liz-henry-being-disabled-tech.html). We could also add the suggestion from @camilasan by the Zoe Henry [link](https://www.inc.com/zoe-henry/aapd-disability-equality-index-2017.html)


@Ayushbajpai19 considering today is Octover 30th I am not sure if you are interested in picking this up still but if you are you could start with a PR for those changes :slightly_smiling_face: :blue_heart:

**Comment by sleepypioneer** [comment]
Note that https://github.com/opensourcediversity/opensourcediversity.org/pull/143#pullrequestreview-1161183731 already updates the link for the Liz Henry article so the potential work here would be to add the Zoe Henry link :)

**Comment by Shu12388y** [comment]
@camilasan hello shubham here can you assign this issue to me i want to work on this issue

**Comment by jonatoni** [comment]
Closing this issue for now - if someone wants to add new article/s, please create a new issue :tada:
