### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by jancborchardt** [opensourcediversity/opensourcediversity.org#47]
While the [Contributor Covenant](https://www.contributor-covenant.org/) is listed on our page as first item, we don’t really explicitly mention that/if we adopted it.

We should mention it:
- [x] In the footer of the website
- [x] In the readme of the repository
- [x] Via a CODEOFCONDUCT file (or so) in the repository

What does everyone think? @camilasan @sleepypioneer @Incabell @jonatoni @22nds @sara-02

**Comment by sleepypioneer** [comment]
oops read that as should we mention it in ;) well I guess I should assign myself now im here 😆 

Not sure the extra file is needed in the repo if its a link to a file?

**Comment by jancborchardt** [comment]
Pull request at https://github.com/opensourcediversity/opensourcediversity.org/pull/61 – please review! :)
