### ISSUE TITLE
Add contact details (signal & IRC links to readme)

### ISSUE THREAD

**Issue by sleepypioneer** [opensourcediversity/opensourcediversity.org#48]
It would be good for new members to have a list of tools for working with us.

**Comment by camilasan** [comment]
For IRC: https://matrix.to/#/!WomCGeovYanLvdUgwo:matrix.org (is this correct @jancborchardt?)
Signal: I don't know how to get the link to a chat room. Anyone?

**Comment by jancborchardt** [comment]
The link to the IRC/Riot room is already on the website in the header. :) But I would consider replacing it with Discourse for reasons mentioned in https://github.com/opensourcediversity/opensourcediversity.org/pull/63#issuecomment-439720337

> - IRC is super hard to use, and Riot only makes it a bit easier
> - Especially now with our Discourse running, it doesn’t make a lot of sense to have another channel
> - The IRC channel is very impermanent compared to Discourse, and quite inactive.
> - Too many different communication platforms for a project are confusing.

What do you think?

As for Signal, the rooms are invite-based so you have to invite people via their phone number. :) I would say now that we have the Discourse forum we should do more and more via there and phase out the Signal group to have things in the open?

**Comment by jancborchardt** [comment]
Closing as #63 is merged, Discourse is now very present. :)
