### ISSUE TITLE
sustainOSS - Invite / Travel Fund available.

### ISSUE THREAD

**Issue by piamancini** [opensourcediversity/opensourcediversity.org#49]
Hi! We are organizing the second edition of [sustainOSS](https://sustainoss.org) in London on the 25th of October.

I'd like to make sure this community gets enough time to buy tickets and/or apply to travel fund to attend. Travel fund closes next week! 

Also, if you are connected with networks of sustainers/ maintainers that are not normally voices in the open source sustainability conversations, could you please share them with me?  We specially want to include them in sustain! (you can find me pia at opencollective dot com)

We are brining people in from Nigeria, South Africa, India, Latin America and Eastern Europe.

Thanks <3

**Comment by jancborchardt** [comment]
@piamancini ah, totally missed this as I was on vacation the whole September. :\

Is anyone else going? And next time we should absolutely spread the word! :)

@piamancini I also just tried adding you to the `@osdiversity` Twitter account via https://tweetdeck.twitter.com, but it said:
> That user has privacy settings enabled preventing them from being added to this team.

**Comment by jancborchardt** [comment]
Closing because the event has passed. @piamancini any time you have a cool event to share, feel free to post it in the Events category of our new forum: https://discourse.opensourcediversity.org – that’s probably much more visible than this Github repo. :slightly_smiling_face:
