### ISSUE TITLE
Add Hacktober Fest in Programs section.

### ISSUE THREAD

**Issue by aSquare14** [opensourcediversity/opensourcediversity.org#52]

**Comment by dipu989** [comment]
I will take up this issue.

**Comment by dipu989** [comment]
@aSquare14 
Done and is ready for review.
Thank You.

**Comment by jancborchardt** [comment]
@dipu989 just saw this – the pull requests are open in your own repository and not in this one. :) Could you combine the commit into one (adding image and text) and open it as a pull request in this repository?

**Comment by dipu989** [comment]
@jancborchardt 
Thanks For Checking the PR.
Sure, I will reopen it within a few days, following the instructions!

**Comment by dipu989** [comment]
@jancborchardt 
I have opened a new PR.
Please have a look.

**Comment by jancborchardt** [comment]
Fixed with https://github.com/opensourcediversity/opensourcediversity.org/pull/67 :) Thanks for your contribution!
