### ISSUE TITLE
Add first contributions in Basics section

### ISSUE THREAD

**Issue by Roshanjossey** [opensourcediversity/opensourcediversity.org#55]
[First contributions](https://github.com/firstcontributions/first-contributions) is a project to help beginners to get started with contributing to open source projects.

We have a hands-on tutorial, a web app to find projects to contribute to and a slack community to ask questions and get help.

Here's a code snippet that could go in to `opensourcediversity.org`

```
<a class="col-md-4" href="https://firstcontributions.github.io" target="_blank" rel="noopener">
	<img alt="" src="https://avatars1.githubusercontent.com/u/37713493?v=4" />
	<h3>First Contributions</h3>
	<p>🚀✨ Help beginners to contribute to open source projects </p>
</a>
```

**Comment by Satyabrat35** [comment]
Can i work on this issue ?

**Comment by Roshanjossey** [comment]
Hi @Satyabrat35, I appreciate your enthusiasm in taking this up. 🖖 

I'm not a maintainer in this project. So, I'm not 100% positive if the maintainers want this change.

Even if that is the case, I'd encourage you to get started by forking this project, cloning and getting familiar with the code. Even if this change is not accepted, you can work on some other issues.

Check out first contributions if you want to learn more about the workflow of contributing through GitHub.

**Comment by Satyabrat35** [comment]
Thank You :+1:

**Comment by palash25** [comment]
@Roshanjossey I was just here to open the same issue :laughing:

**Comment by jancborchardt** [comment]
Sounds great! 🙋 Do open a pull request to add it to the basics section, would be awesome to have it in.

The snippet in the first post seems good except 2 things:
- The image should not be hotlinked but rather added to the project images folder here
- A better description might be "Make your first open source contribution in 5 minutes", just like on the website? (Feel free to keep the glitter emojo though :wink:)

Thanks and welcome! :tada:

**Comment by Roshanjossey** [comment]
@jancborchardt, Thank you for your response 🖖 

@Satyabrat35, jump in.

**Comment by syauqy** [comment]
Hi, I just saw this issue and did an update for it, please check this PR #86

**Comment by Rishi007-web** [comment]
Is this issue is resolved?
If not I want to work on basics section

**Comment by pdurbin** [comment]
@Rishi007-web it looks like @syauqy already opened pull request #86 to close this issue.

**Comment by jancborchardt** [comment]
Aaand merged the pull request https://github.com/opensourcediversity/opensourcediversity.org/pull/86 by @syauqy! :) Sorry for the lateness – anyone can review pull requests. :)
