### ISSUE TITLE
Smooth Scrolling when clicked on elements of navigation bar

### ISSUE THREAD

**Issue by plxity** [opensourcediversity/opensourcediversity.org#58]
To make the UI/UX better we can smooth scrolling effect on the navigation bar elements.

**Comment by jancborchardt** [comment]
@plxity good point! Do you want to work on that? :)

**Comment by plxity** [comment]
@jancborchardt Yes sure.

**Comment by jancborchardt** [comment]
Fixed by @RocktimSaikia via https://github.com/opensourcediversity/opensourcediversity.org/pull/76 – thanks a lot! :)
