### ISSUE TITLE
Impressum Set Up 

### ISSUE THREAD

**Issue by samu-workopen** [opensourcediversity/opensourcediversity.org#6]
*contact people 
*DSGVO

**Comment by jancborchardt** [comment]
We can then also put some additional credits / legal info in the imprint:

- All [code open source](https://github.com/opensourcediversity) under [AGPLv3+](https://www.gnu.org/licenses/agpl-3.0.en.html), all content [Creative Commons Attribution-ShareAlike](https://creativecommons.org/licenses/by-sa/4.0/)
- Logo by [Elio Qoshi](https://elioqoshi.me) of [Ura Design](https://ura.design) & [Open Source Design](https://opensourcedesign.net)
- [Nunito typeface](https://github.com/vernnobile/NunitoFont) by [Vernon Adams](http://sansoxygen.com)

**Comment by jwflory** [comment]
Hi all, I am cleaning up and triaging some old issues to figure out where we are on website development in 2021. I am closing this issue as we get back up to speed on the current backlog on the site. 🎬
