### ISSUE TITLE
Custom font on the site doesn't load (broken link)

### ISSUE THREAD

**Issue by alicetragedy** [opensourcediversity/opensourcediversity.org#74]
The URL for the font in the css points to `../fonts/Nunito-Bold.ttf` but the font files are located in the `css` folder. Either the URL should be updated accordingly, or the files should be moved to a new `fonts` folder in the root (probably depending on what y'all prefer, structure-wise). 

This would be a really good first issue for someone looking to contribute ✨

**Comment by jancborchardt** [comment]
Yes, a very good first issue!

> Either the URL should be updated accordingly, or the files should be moved to a new fonts folder in the root (probably depending on what y'all prefer, structure-wise).

The URL can simply be updated from `fonts` to `css`, less folders is nice. :)

**Comment by adzshaf** [comment]
@jancborchardt hi! can I work on this issue? Thank you!

**Comment by jancborchardt** [comment]
@adzshaf yes, that would be very cool! If you have any questions, we're available. :)
