### ISSUE TITLE
Retaining women in open source: Organising open source day monthly

### ISSUE THREAD

**Issue by tapaswenipathak** [opensourcediversity/opensourcediversity.org#83]
Hi folks: Finding an active open source contributor or maintainer woman is hard. Internships give a break in open source, if observed there is no retention of women in open source and research[1] suggests. Implementing open source day per month letting woman work with mentor and contribute in an open source project they would like would be practical implementation than just publishing research and articles. Lemme know if you would interested in supporting and I will share further things.

[1] https://en.wikipedia.org/wiki/Diversity_in_open-source_software

**Comment by jancborchardt** [comment]
@tapaswenipathak that would be cool! I’d say a better place to discuss an event would be the forum at https://discourse.opensourcediversity.org/ since we also have the "Events" subcategory there which we use for organizing, and other events get posted too. :)

**Comment by tapaswenipathak** [comment]
On Mon, Aug 26, 2019 at 9:35 PM Jan-Christoph Borchardt
<notifications@github.com> wrote:
>
> @tapaswenipathak that would be cool! I’d say a better place to discuss an event would be the forum at https://discourse.opensourcediversity.org/ since we also have the "Events" subcategory there which we use for organizing, and other events get posted too. :)

Hello,

I will be mailing the proposal out as well. :)

>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by jancborchardt** [comment]
Cool, closing this then, let’s move the conversation to the forum. :)
