### ISSUE TITLE
[Idea][Section on Newletters]

### ISSUE THREAD

**Issue by sara-02** [opensourcediversity/opensourcediversity.org#84]
Just floating an idea:
There are some great Newsletters run by the likes of [DiversifyTech](https://www.diversifytech.co/), [CodeNewBie](https://www.codenewbie.org/), and other main stream organizations like the [CODE Reviews](https://us7.campaign-archive.com/home/?u=e75be710ba1a2eb0df9d82ca4&id=73a7096e5d) by Women Who Code.
Can we have a section highlighting these Newsletters?

**Comment by jancborchardt** [comment]
@sara-02 maybe it would be cool to open a thread on the forum https://discourse.opensourcediversity.org to list the ones you know about already and collect more newsletters like that? :) (Also to find if there are any specifically at the intersection of _open source_ and _diversity_, as most is general "tech" and diversity.)

**Comment by jonatoni** [comment]
Thanks for the idea @sara-02 :tada: it would be great if you can open a thread on our forum (as Jan mentioned) - so we can gather more feedback from other community folks :tada: 

Closing this issue as stale for now
