### ISSUE TITLE
How do I become a member of this community?

### ISSUE THREAD

**Issue by ucalyptus** [opensourcediversity/opensourcediversity.org#89]
Please go through my profile, @ucalyptus

**Comment by jancborchardt** [comment]
Everyone who works on diversity & inclusion in open source is a member. :)
Come introduce yourself in the introductory thread in the forum at https://discourse.opensourcediversity.org/t/introductions-come-in-say-hi/19/
You are now also added to the Github organization here, but this is not a requirement to contribute. :)
