### ISSUE TITLE
Check accessability

### ISSUE THREAD

**Issue by sleepypioneer** [opensourcediversity/opensourcediversity.org#9]
Should check through site for accessability, this ranges from correct alt="" in images but also some formatting. This can be checked with google chrome audits in the developer tools. (See image)

![audits](https://user-images.githubusercontent.com/23617373/40686853-fdc6b478-6398-11e8-9a12-ec74e594ad23.PNG)

**Comment by jancborchardt** [comment]
Good point!

So embarrassed I missed the empty alt tags for decorative images that I fixed it right away :O https://github.com/opensourcediversity/opensourcediversity.org/commit/8bf9fef3a7b01c97a5c5d07d69ff66182533c2e6
Also did a first compression of the project images.

[WAVE](https://wave.webaim.org/) has no other complaints for now, will go through it with Lighthouse tomorrow.

**Comment by sleepypioneer** [comment]
Dont panic, It will be something that needs checking at regular intervals. Colours can also be an issue it will probably not like the menu buttons contrast in the top nav.

**Comment by 22nds** [comment]
@sleepypioneer Checked the color contrast of background color #45B086 and white and the contrast ratio is only 2.69:1 - which fails WCAG. 

Solution would be to make green darker (eg. #28624E) or color of the text black (which also means black background). I am in favour of darkening the green - but ultimately this is a design decision. 

![dark-green](https://user-images.githubusercontent.com/1879220/40715031-90b6bea2-6404-11e8-955f-64ac15566035.png)

The site itself could also benefit from greater line height and spacing between rows of elements.

**Comment by sleepypioneer** [comment]
Hi @22nds great to see you here! @jancborchardt is our design Guru so I will leave this to him, thanks for checking :)

**Comment by jancborchardt** [comment]
I enhanced the readability a bit:
- Added a slight text-shadow to the white text which on green
- Made the navigation text fully opaque white by default
- Added the hover/focus effect for the navigation links too
![screenshot from 2018-05-30 14-29-12](https://user-images.githubusercontent.com/925062/40721388-a6ccea58-6419-11e8-85e8-9754bc572c2b.png)


Changing the text/foreground color from white to dark definitely looks a bit negative (or what do you think?):
![screenshot from 2018-05-30 14-53-33](https://user-images.githubusercontent.com/925062/40722345-5a28cb6a-641c-11e8-81a3-58b4c1080bf4.png)

Darkening the background color also makes it a bit gloomy, but maybe we need to find the correct balance there?

> The site itself could also benefit from greater line height and spacing between rows of elements.

@22nds great point! Fixed it with https://github.com/opensourcediversity/opensourcediversity.org/commit/e74222e813ffc6665790905199fd24fa8a6b7c1e

I’ll look into changing the Light & Semibold font combination to Regular & Bold for better readability.

**Comment by jancborchardt** [comment]
Fonts are now changed to Regular & Bold, much better! :)

And a pull request with compressed images is at https://github.com/opensourcediversity/opensourcediversity.org/pull/16

**Comment by jancborchardt** [comment]
Closing as we fixed the basic issues. If there’s stuff left or new things coming up, please open new issues! :)
