### ISSUE TITLE
Explicitly label promo content as CC?

### ISSUE THREAD

**Issue by SantiagoTorres** [opensourcediversity/opensourcediversity.org#92]
I was hoping to print and distribute logos/stickers and whatnot. I'd like these resources to be CC-BY or so for doing it :)

**Comment by jancborchardt** [comment]
They are explicitly licensed as CC-BY in the readme at https://github.com/opensourcediversity/opensourcediversity.org#-license :) And directly below that:

> Everyone is welcome to print material and present Open Source Diversity at events – permission is not needed, everyone in the community can help! :blush:

So please do go ahead :)
