### ISSUE TITLE
Adding "First Timers Only" on basics section

### ISSUE THREAD

**Issue by Chris2W** [opensourcediversity/opensourcediversity.org#94]
I thought it would be nice to provide additional guidance for newbies diving into open source... https://www.firsttimersonly.com/ provides a beginner friendly outline and resource that I personally used to get into open source. While it mentions UpForGrabs and Code of Conduct like in Open Source Diversity, it also mentions platforms like CodeTriage and many other things that I believe can be vital in guiding beginners towards open source contributing. What do you think?

**Comment by tosinibrahim96** [comment]
A [PR ](https://github.com/opensourcediversity/opensourcediversity.org/pull/95)has been merged to address this issue already. Maybe this issue should be closed now.
