### ISSUE TITLE
Add DISCOVER cookbook 

### ISSUE THREAD

**Issue by OriolAbril** [opensourcediversity/opensourcediversity.org#99]
I think that https://github.com/numfocus/DISCOVER-Cookbook would be a good fit for the projects section of the home page

**Comment by pranavvp10** [comment]
Hi there, I am interested in working on this issue if it is still available. @OriolAbril

**Comment by sleepypioneer** [comment]
Fixed in https://github.com/opensourcediversity/opensourcediversity.org/pull/110
